const SK_STORAGE="spielzaehler-skullking-v1";
function skLoad(){try{return JSON.parse(localStorage.getItem(SK_STORAGE))}catch{return null}}
function skSave(s){localStorage.setItem(SK_STORAGE,JSON.stringify(s))}
function skNew(){return {phase:"setup",round:1,players:[],history:[]}}
function skCalc(round,bid,tricks,bonus){bid=Number(bid);tricks=Number(tricks);bonus=Number(bonus)||0;if(bid===0)return (tricks===0?1:-1)*round*10+(tricks===0?bonus:0);if(bid===tricks)return bid*20+bonus;return -10*Math.abs(bid-tricks)}
function skTotals(s){const t=Object.fromEntries(s.players.map(p=>[p.id,0]));s.history.forEach(r=>Object.entries(r.scores).forEach(([id,v])=>t[id]=(t[id]||0)+v));return t}
function skPlayerFields(n=3){return Array.from({length:n},(_,i)=>'<input class="text-input sk-name" placeholder="Spieler '+(i+1)+'" maxlength="24" autocomplete="off">').join("")}
function renderSkullKing(){let s=skLoad()||skNew();title.textContent="Skull King";app.replaceChildren();const root=document.createElement("section");root.className="stack sk-view";
 if(s.phase==="setup"){root.innerHTML='<section class="card stack compact"><p class="eyebrow">Neue Partie</p><h2>Crew zusammenstellen</h2><div id="sk-names" class="player-fields">'+skPlayerFields(3)+'</div><button class="secondary-button" id="sk-add" type="button">+ Person</button><button class="primary-button" id="sk-start" type="button">Partie starten</button></section>';app.append(root);return}
 const totals=skTotals(s);root.innerHTML='<div class="sk-scoreboard">'+s.players.map(p=>'<div class="score-card"><span>'+escapeHtml(p.name)+'</span><strong>'+formatScore(totals[p.id])+'</strong></div>').join("")+'</div><section class="card sk-round-head"><div><p class="eyebrow">Runde '+s.round+' von 10</p><h2>'+s.round+' Karte'+(s.round===1?"":"n")+' pro Person</h2></div></section><div id="sk-stage"></div><section><div class="section-heading"><h2>Spielblock</h2></div><div class="sk-history">'+(s.history.length?s.history.map(r=>'<div class="round-card sk-history-row"><strong>Runde '+r.round+'</strong>'+s.players.map(p=>'<span>'+escapeHtml(p.name)+': '+formatScore(r.scores[p.id])+'</span>').join("")+'</div>').reverse().join(""):'<div class="empty-state">Noch keine Runde gewertet.</div>')+'</div></section><button class="danger-button" id="sk-reset" type="button">Partie löschen</button>';app.append(root);skRenderStage(s)}
function skRenderStage(s){const stage=document.querySelector("#sk-stage");if(!stage)return;
 if(s.phase==="bid"){stage.innerHTML='<section class="card stack compact"><div><p class="eyebrow">Vor der Runde</p><h2>Stiche ansagen</h2><p class="sk-help">Jeder zeigt jetzt seine Ansage. Danach werden die Ansagen gesperrt.</p></div><div class="sk-input-grid">'+s.players.map(p=>'<label><span>'+escapeHtml(p.name)+'</span><select data-sk-bid="'+p.id+'">'+Array.from({length:s.round+1},(_,i)=>'<option value="'+i+'">'+i+'</option>').join("")+'</select></label>').join("")+'</div><button class="primary-button" id="sk-lock-bids">Ansagen festlegen</button></section>';return}
 if(s.phase==="play"){stage.innerHTML='<section class="card stack compact"><div><p class="eyebrow">Runde '+s.round+'</p><h2>Ergebnis eintragen</h2></div><div class="sk-bids">'+s.players.map(p=>'<div><span>'+escapeHtml(p.name)+'</span><strong>Ansage: '+s.bids[p.id]+'</strong></div>').join("")+'</div><div class="sk-result-grid">'+s.players.map(p=>'<div class="sk-result"><strong>'+escapeHtml(p.name)+'</strong><label>Stiche<select data-sk-tricks="'+p.id+'">'+Array.from({length:s.round+1},(_,i)=>'<option value="'+i+'">'+i+'</option>').join("")+'</select></label><label>Bonus<input class="score-input" data-sk-bonus="'+p.id+'" type="number" inputmode="numeric" min="0" step="10" value="0"></label></div>').join("")+'</div><button class="primary-button" id="sk-score">Runde werten</button></section>';return}
 stage.innerHTML='<section class="card stack compact"><p class="eyebrow">Fertig</p><h2>10 Runden gespielt</h2></section>'}
app.addEventListener("click",e=>{if(view.name!=="skullking")return;let s=skLoad()||skNew();
 if(e.target.id==="sk-add"){document.querySelector("#sk-names").insertAdjacentHTML("beforeend",skPlayerFields(1));return}
 if(e.target.id==="sk-start"){const names=[...document.querySelectorAll(".sk-name")].map(x=>x.value.trim()).filter(Boolean);if(names.length<2)return alert("Mindestens zwei Spieler.");s={phase:"bid",round:1,players:names.map(name=>({id:makeId(),name})),history:[]};skSave(s);renderSkullKing();return}
 if(e.target.id==="sk-lock-bids"){s.bids={};document.querySelectorAll("[data-sk-bid]").forEach(x=>s.bids[x.dataset.skBid]=Number(x.value));s.phase="play";skSave(s);skRenderStage(s);return}
 if(e.target.id==="sk-score"){const scores={},results={};s.players.forEach(p=>{const tricks=Number(document.querySelector('[data-sk-tricks="'+p.id+'"]').value);const bonus=Number(document.querySelector('[data-sk-bonus="'+p.id+'"]').value)||0;scores[p.id]=skCalc(s.round,s.bids[p.id],tricks,bonus);results[p.id]={bid:s.bids[p.id],tricks,bonus}});s.history.push({round:s.round,scores,results});if(s.round>=10)s.phase="done";else{s.round++;s.phase="bid";delete s.bids}skSave(s);renderSkullKing();return}
 if(e.target.id==="sk-reset"&&confirm("Skull-King-Partie wirklich löschen?")){localStorage.removeItem(SK_STORAGE);renderSkullKing()}})
